### ISSUE TITLE
Switch from Phantomjs to Headless Chrome

### ISSUE THREAD

**Issue by grantat** [erikaris/web-memento-damage#15]
https://groups.google.com/forum/m/#!topic/phantomjs/9aI5d-LDuNE phantomjs will no longer be maintained. Might be a good time to switch over to headless chrome.

**Comment by erikaris** [comment]
Hi Grant, 

Yes, I already knew about it and still try to do a migration from phantomjs to headless chrome. Thank you for reminding me :)
Btw, if you have any comment or feedback regarding the Memento-Damage, please feel free to contact me. 
Thank you. 

Erika
