### ISSUE TITLE
Screenshot has superfluous scroll bars

### ISSUE THREAD

**Issue by machawk1** [erikaris/web-memento-damage#5]
Within the main UI there exists a "Screenshots" icon/tab.

The image shown in this tab differs from what I currently see in my browser in unexpected ways that are difficult to attribute to the full-page rendering. As an example, https://nasa.gov from the Damage service:

![http- 2f 2fnasa](https://cloud.githubusercontent.com/assets/2514780/22112962/cbe0d53e-de32-11e6-8ee5-67704208851b.jpg)

vs. what I see in my browser:
![screen shot 2017-01-19 at 10 30 50 am](https://cloud.githubusercontent.com/assets/2514780/22112993/e21ff410-de32-11e6-8dc5-3177e7fc2c88.png)

Note the strange scrollbars over the blue [meatball](https://en.wikipedia.org/wiki/NASA_insignia#/media/File:NASA_logo.svg) image.

**Comment by erikaris** [comment]
Hi @machawk1,
Did you run this URI [https://nasa.gov/](url) using the web service on [http://wsdl-docker.cs.odu.edu:8880/](url)? What browser did you use? 
I run the URI using 4 different browsers: Firefox, Chrome, Ubuntu web browser, and Vivaldi. I also run the URI on 3 different versions of memento-damage: the one that runs on [http://wsdl-docker.cs.odu.edu:8880/](url), the one that runs on my local docker, and the non-docker version in my local machine. But I cannot find any strange scroll bars. 
Here is the screenshot that I got:
![nasa_nondocker_local_chrome](https://cloud.githubusercontent.com/assets/16355740/22282424/35eef624-e2aa-11e6-8713-e77b2cd53bae.jpg)

Could you please try to run the URI again and see if the 'superfluous scrollbars' still exist?
Thanks.

**Comment by machawk1** [comment]
@erikaris I am using the instance at http://memento-damage.erikasiregar.tk/memento/check?url=http://nasa.gov&type=URI-M&fresh=false&fresh=true . I cannot replicate this screenshot at  http://wsdl-docker.cs.odu.edu:8880/ . Is the instance at http://memento-damage.erikasiregar.tk an old version?

I am running Chrome on macOS.

**Comment by erikaris** [comment]
Yes, the one that is running on http://memento-damage.erikasiregar.tk/ is the old version and no longer exist. I think the "superfluous scroll bars" problem happened because you used the older version.  
Right now, anyone who accesses the old version will be automatically redirected to http://memento-damage.cs.odu.edu/. 
Could you please try it again and let me know if the scrollbar problem persists?

**Comment by machawk1** [comment]
@erikaris The screenshot is never shown when I use http://memento-damage.erikasiregar.tk/ now with `http://nasa.gov`. An HTTP 500 is displayed in the console.
![screen shot 2017-01-28 at 10 04 36 pm](https://cloud.githubusercontent.com/assets/2514780/22401546/e35022a4-e5a5-11e6-9658-7178ae450695.png)

**Comment by erikaris** [comment]
I did not get this error when I run http://nasa.gov using the docker instance of memento-damage that run on my local machine. 
![image](https://cloud.githubusercontent.com/assets/16355740/22432891/7b527d60-e6e4-11e6-98da-2ff28311e811.png)

Perhaps there is a problem with the service that runs on http://memento-damage.cs.odu.edu/. 
I will send an email to Sawood to ask him to re-run the docker image and see if it can solve the problem or not. 
In the meantime, maybe you could run the docker instance and see if it still return the same error?
Thanks.

**Comment by machawk1** [comment]
@erikaris Can you replicate the error for `nasa.gov` at http://memento-damage.erikasiregar.tk/?

**Comment by erikaris** [comment]
The service on http://memento-damage.erikasiregar.tk/ is no longer exists and you will be automatically redirected to http://memento-damage.cs.odu.edu/. There is no superfluous scrollbar in this new memento-damage version. 
Do I have to replicate the error for nasa.gov at http://memento-damage.erikasiregar.tk/? I think I can try to revive the old version and see the error...

**Comment by machawk1** [comment]
@erikaris http://memento-damage.cs.odu.edu/memento/check/?url=http%3A%2F%2Fnasa.gov#screenshots reports the same Error 500. No screenshot is shown. I cannot verify that the scrollbar issue does not exist in an undisplayed screenshot.

**Comment by erikaris** [comment]
Sawood just restart the service for http://memento-damage.cs.odu.edu/. I have tried it for http://nasa.gov: http://memento-damage.cs.odu.edu/memento/check/?url=https%3A%2F%2Fwww.nasa.gov%2F&fresh=true#summary  and it works well.

**Comment by machawk1** [comment]
LGTM
