### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by machawk1** [erikaris/web-memento-damage#6]
I, and potentially others, hope to reuse this code but a barrier in doing so (namely, for others) is that there is no explicit LICENSE file in the repo nor any mention in the README. Please consider adding one.

**Comment by erikaris** [comment]
Hi Mat,

Thank you for this feedback. I haven't updated the README file since a long
time ago. I know this is bad :( . Looks like I have a lot of homework to
do.
Thank you so much.

Regards,

Erika

**Comment by machawk1** [comment]
@erikaris This ticket can be accomplish solely within the GitHub web user interface. Simply click on the CREATE NEW FILE button, type LICENSE as the filename then select an appropriate license in the dropdown to the right. For reference, I have used the MIT License in a few past projects.
